server:
  port: 9001
Spring:
  application:
    name: nacos-provider
    cloud:
      discovery:
        server-addr: 169.254.47.44:8848

management:
  endpoint:
    web:
      exposure:
        include: '*'