server:
  port: 9002
Spring:
  application:
    name: nacos-provider-01
    cloud:
      discovery:
        server-addr: 169.254.47.44:8848

management:
  endpoint:
    web:
      exposure:
        include: '*'